# Generated by Django 5.0.1 on 2026-01-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Version of analysis algorithm used. Enables batch re-processing when improved.",
                        max_length=20,
                    ),
                ),
                ("flow_score", models.FloatField()),
                ("flow_score_rating", models.CharField(max_length=20)),
                ("stability_index_percent", models.FloatField()),
                ("flexion_index_percent", models.FloatField()),
                ("barn_door_events", models.IntegerField()),
                ("avg_hip_distance", models.FloatField()),
                ("frame_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
